# Stage 1: Build the React Application
FROM node:20-alpine AS build
WORKDIR /app
COPY apps/frontend/package*.json ./
RUN npm install
COPY apps/frontend/ ./
RUN npm run build

# Stage 2: Serve the build static assets using Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY deployment/docker/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
