from enum import Enum

class CaseStatus(str, Enum):
    CREATED = "CREATED"
    INVESTIGATING = "INVESTIGATING"
    EVIDENCE_REVIEW = "EVIDENCE_REVIEW"
    POLICY_REVIEW = "POLICY_REVIEW"
    FRAUD_REVIEW = "FRAUD_REVIEW"
    RESOLUTION_PENDING = "RESOLUTION_PENDING"
    HUMAN_REVIEW = "HUMAN_REVIEW"
    APPROVED = "APPROVED"
    EXECUTING = "EXECUTING"
    RESOLVED = "RESOLVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"

class AgentRunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    WAITING_HUMAN = "WAITING_HUMAN"

class ResolutionStatus(str, Enum):
    PROPOSED = "PROPOSED"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXECUTED = "EXECUTED"
    FAILED = "FAILED"

class UserRole(str, Enum):
    CUSTOMER = "CUSTOMER"
    SUPPORT_AGENT = "SUPPORT_AGENT"
    FRAUD_ANALYST = "FRAUD_ANALYST"
    POLICY_ANALYST = "POLICY_ANALYST"
    RESOLUTION_MANAGER = "RESOLUTION_MANAGER"
    ADMIN = "ADMIN"
