from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from libs.db_shared.session import get_db
from libs.db_shared.models.user import User
from app.api.deps import get_current_user, require_permission
from app.core.permissions import AUDIT_VIEW, RESOLUTION_APPROVE
from apps.ai_engine.knowledge.case_memory import CASE_MEMORY_DB, CaseMemoryStore
from typing import List, Dict, Any, Optional

router = APIRouter()

# In-memory learning insights store
LEARNING_INSIGHTS_DB: List[Dict[str, Any]] = [
    {
        "insight_id": "INS-9001",
        "category": "Evidence Quality",
        "title": "Delivery Photograph Requirement for Damaged Claims",
        "insight_text": "18% of damaged-product claims require human manager review because uploaded unboxing photo resolution is insufficient.",
        "recommendation": "Request a delivery photo during complaint intake to verify outer box transit damage automatically.",
        "impact_assessment": "Estimated to reduce avoidable human escalations by 24%.",
        "status": "PROPOSED",
        "requires_human_approval": True,
        "data_source": "demo_seed"
    },
    {
        "insight_id": "INS-9002",
        "category": "Policy Friction",
        "title": "High-Value Threshold Policy WARRANTY-4.2 Alignment",
        "insight_text": "Claims between INR 45,000 and INR 50,000 frequently hit policy conflict rules under HIGHVALUE-1.2.",
        "recommendation": "Align Policy Section 1.2 high-value verification threshold with VIP customer loyalty scores.",
        "impact_assessment": "Improves VIP resolution speed by 85% while keeping fraud risk under control.",
        "status": "PROPOSED",
        "requires_human_approval": True,
        "data_source": "demo_seed"
    },
    {
        "insight_id": "INS-9003",
        "category": "Customer Satisfaction",
        "title": "Replacement vs Partial Refund Preference Pattern",
        "insight_text": "Customers report 4.7/5 satisfaction for replacements compared to 3.8/5 for partial refund vouchers.",
        "recommendation": "Prioritize warehouse replacement reservation whenever inventory stock level > 5 units.",
        "impact_assessment": "Boosts overall customer CSAT by +0.9 points.",
        "status": "APPROVED",
        "approved_by": "admin@resolve.ai",
        "data_source": "demo_seed"
    }
]

@router.get("/insights")
def list_learning_insights(
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Retrieve continuous improvement insights generated by Learning Agent."""
    return LEARNING_INSIGHTS_DB

@router.post("/insights/{insight_id}/approve")
def approve_learning_insight(
    insight_id: str,
    current_user: User = Depends(require_permission(RESOLUTION_APPROVE)),
    db: Session = Depends(get_db)
):
    """Human admin approves a proposed learning recommendation."""
    for ins in LEARNING_INSIGHTS_DB:
        if ins["insight_id"] == insight_id:
            ins["status"] = "APPROVED"
            ins["approved_by"] = current_user.email
            return {"insight_id": insight_id, "status": "APPROVED", "message": f"Insight '{ins['title']}' approved by {current_user.email}."}

    raise HTTPException(status_code=404, detail=f"Insight '{insight_id}' not found.")

@router.post("/insights/{insight_id}/reject")
def reject_learning_insight(
    insight_id: str,
    current_user: User = Depends(require_permission(RESOLUTION_APPROVE)),
    db: Session = Depends(get_db)
):
    """Human admin rejects a proposed learning recommendation."""
    for ins in LEARNING_INSIGHTS_DB:
        if ins["insight_id"] == insight_id:
            ins["status"] = "REJECTED"
            ins["rejected_by"] = current_user.email
            return {"insight_id": insight_id, "status": "REJECTED", "message": f"Insight '{ins['title']}' rejected by {current_user.email}."}

    raise HTTPException(status_code=404, detail=f"Insight '{insight_id}' not found.")

@router.get("/cases")
def search_case_memory(
    category: Optional[str] = None,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Browse historical cases stored in Case Memory layer."""
    if category:
        return CaseMemoryStore.search_similar_cases(category=category, limit=10)
    return CASE_MEMORY_DB
